# Site Settings

title: Ars Mentis
subtitle: Custom Software and IT Consulting
author:
  name: Ars Mentis, LLC
  email: james@arsentis.com
description: >
  Custom software solutions for clients of any size. All problems have solutions.
  Let me solve yours.
baseurl: "am-j2" # the subpath of your site, e.g. /blog/
url: "https://skbruck.github.io/am-j2/" # the base hostname & protocol for your site

exclude: ['Gemfile', 'Gemfile.lock', 'README.md', 'LICENSE']
permalink: pretty

kramdown:
  input: GFM

# plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap